# Generated by Django 4.1.6 on 2023-02-26 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_task_delete_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В процессе'), ('Ended', 'Выполнена')], default='New', max_length=20, verbose_name='Статус'),
        ),
    ]
